In [1]:
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
from pathlib import Path
from IPython.display import display

In [2]:
DATA_PATH = Path("../datasets").resolve()
datasets = list(DATA_PATH.glob("*.csv", case_sensitive=False))

if not datasets:
    kagglehub.dataset_download(
        handle="blastchar/telco-customer-churn",
        force_download=True,
        output_dir=DATA_PATH
    )
    
datasets

[WindowsPath('D:/Users/Esperine/Workspace3/mlzc-main/datasets/data.csv'),
 WindowsPath('D:/Users/Esperine/Workspace3/mlzc-main/datasets/WA_Fn-UseC_-Telco-Customer-Churn.csv')]

In [3]:
df = pd.read_csv(datasets[1])
print(df.shape)
df.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [5]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [7]:
def normalize_name(s: str) -> str:
    # Insert underscore between consecutive capitals followed by lowercase (e.g., 'XMLHttp' -> 'XML_Http')
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", s)
    # Insert underscore between lowercase/numbers and following uppercase (e.g., 'HttpReq' -> 'Http_Req')
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)

    return s.lower()

In [8]:
df.rename(columns=normalize_name).columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'monthly_charges', 'total_charges', 'churn'],
      dtype='str')

In [9]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
df.columns = df.rename(columns=normalize_name).columns

categorical_columns = list(df.dtypes[df.dtypes == "str"].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-vhveg,female,0,yes,no,1,no,no_phone_service,dsl,no,...,no,no,no,no,month-to-month,yes,electronic_check,29.85,29.85,no
1,5575-gnvde,male,0,no,no,34,yes,no,dsl,yes,...,yes,no,no,no,one_year,no,mailed_check,56.95,1889.5,no
2,3668-qpybk,male,0,no,no,2,yes,no,dsl,yes,...,no,no,no,no,month-to-month,yes,mailed_check,53.85,108.15,yes
3,7795-cfocw,male,0,no,no,45,no,no_phone_service,dsl,yes,...,yes,yes,no,no,one_year,no,bank_transfer_(automatic),42.30,1840.75,no
4,9237-hqitu,female,0,no,no,2,yes,no,fiber_optic,no,...,no,no,no,no,month-to-month,yes,electronic_check,70.70,151.65,yes

In [11]:
df.dtypes

customer_id              str
gender                   str
senior_citizen         int64
partner                  str
dependents               str
tenure                 int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges            str
churn                    str
dtype: object

In [12]:
pd.to_numeric(df["total_charges"])

ValueError: Unable to parse string "_" at position 488

In [14]:
tc = pd.to_numeric(df["total_charges"], errors="coerce")
tc.isna().sum().item()

11

In [15]:
# df[tc.isnull()][["customer_id", "total_charges"]]
df[tc.isna()]

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
488,4472-lvygi,female,0,yes,yes,0,no,no_phone_service,dsl,yes,...,yes,yes,yes,no,two_year,yes,bank_transfer_(automatic),52.55,_,no
753,3115-czmzd,male,0,no,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.25,_,no
936,5709-lvoeq,female,0,yes,yes,0,yes,no,dsl,yes,...,yes,no,yes,yes,two_year,no,mailed_check,80.85,_,no
1082,4367-nuyao,male,0,yes,yes,0,yes,yes,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,25.75,_,no
1340,1371-dwpaz,female,0,yes,yes,0,no,no_phone_service,dsl,yes,...,yes,yes,yes,no,two_year,no,credit_card_(automatic),56.05,_,no
3331,7644-omvmy,male,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,19.85,_,no
3826,3213-vvolg,male,0,yes,yes,0,yes,yes,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,25.35,_,no
4380,2520-sgtta,female,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,two_year,no,mailed_check,20.00,_,no
5218,2923-arzlg,male,0,yes,yes,0,yes,no,no,no_internet_service,...,no_internet_service,no_internet_service,no_internet_service,no_internet_service,one_year,yes,mailed_check,19.70,_,no
6670,4075-wkniu,female,0,yes,yes,0,yes,yes,dsl,no,...,yes,yes,yes,no,two_year,no,mailed_check,73.35,_,no
6754,2775-sefee,male,0,no,yes,0,yes,yes,dsl,yes,...,no,yes,no,no,two_year,yes,bank_transfer_(automatic),61.90,_,no

In [16]:
tc.isna()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: total_charges, Length: 7043, dtype: bool

In [17]:
df["total_charges"] = pd.to_numeric(df["total_charges"], errors="coerce").fillna(0)
df["total_charges"].isna().sum()

np.int64(0)

In [18]:
(df["churn"] == "yes").astype(int)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [19]:
df["churn"] = (df["churn"] == "yes").astype(int)

In [20]:
df.head().transpose()

,0,1,2,3,4
customer_id,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
senior_citizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phone_service,no,yes,yes,no,yes
multiple_lines,no_phone_service,no,no,no_phone_service,no
internet_service,dsl,dsl,dsl,dsl,fiber_optic
online_security,no,yes,yes,yes,no
online_backup,yes,no,yes,no,no
device_protection,no,yes,no,yes,no
tech_support,no,no,no,yes,no
streaming_tv,no,no,no,no,no
streaming_movies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperless_billing,yes,no,yes,no,yes
payment_method,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthly_charges,29.85,56.95,53.85,42.3,70.7
total_charges,29.85,1889.5,108.15,1840.75,151.65
churn,0,0,1,0,1

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        7043 non-null   str
 1   gender             7043 non-null   str
 2   senior_citizen     7043 non-null   int64
 3   partner            7043 non-null   str
 4   dependents         7043 non-null   str
 5   tenure             7043 non-null   int64
 6   phone_service      7043 non-null   str
 7   multiple_lines     7043 non-null   str
 8   internet_service   7043 non-null   str
 9   online_security    7043 non-null   str
 10  online_backup      7043 non-null   str
 11  device_protection  7043 non-null   str
 12  tech_support       7043 non-null   str
 13  streaming_tv       7043 non-null   str
 14  streaming_movies   7043 non-null   str
 15  contract           7043 non-null   str
 16  paperless_billing  7043 non-null   str
 17  payment_method     7043 non-null   str
 18  monthly_charges    7043 non-null   float64
 19  total_charges      7043 non-null   float64
 20  churn              7043 non-null   int64
dtypes: float64(2), int64(3), str(16)
memory usage: 1.8 MB

## Validation framework

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
# Set aside the test set - 20% of all the data
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

# From the remaining 80% of all the data, call the full train set, then split into train and validation
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [24]:
# Resetting indices
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_full_train = df_full_train.reset_index(drop=True)

In [25]:
# Extract target
y_train = df_train["churn"].values
y_val = df_val["churn"].values
y_test = df_test["churn"].values

In [26]:
# Remove target from dataframes
df_train.drop("churn", axis=1, inplace=True)
df_val.drop("churn", axis=1, inplace=True)
df_test.drop("churn", axis=1, inplace=True)

## EDA

In [27]:
df_full_train.isnull().sum()

customer_id          0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

In [28]:
df_full_train["churn"].value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [29]:
df_full_train["churn"].mean().item()

0.26996805111821087

Note that about 73% of the customers stayed and 27% churned. The churn rate is the latter.

In [30]:
df_full_train.dtypes

customer_id              str
gender                   str
senior_citizen         int64
partner                  str
dependents               str
tenure                 int64
phone_service            str
multiple_lines           str
internet_service         str
online_security          str
online_backup            str
device_protection        str
tech_support             str
streaming_tv             str
streaming_movies         str
contract                 str
paperless_billing        str
payment_method           str
monthly_charges      float64
total_charges        float64
churn                  int64
dtype: object

In [31]:
numerical_features = ["tenure", "monthly_charges", "total_charges"]
print(numerical_features)

exclude_cols = numerical_features[:]
exclude_cols.extend(["churn", "customer_id"])
print(exclude_cols)

['tenure', 'monthly_charges', 'total_charges']
['tenure', 'monthly_charges', 'total_charges', 'churn', 'customer_id']

In [32]:
categorical_features = df_full_train.columns.difference(exclude_cols, sort=False).to_list()
categorical_features

['gender',
 'senior_citizen',
 'partner',
 'dependents',
 'phone_service',
 'multiple_lines',
 'internet_service',
 'online_security',
 'online_backup',
 'device_protection',
 'tech_support',
 'streaming_tv',
 'streaming_movies',
 'contract',
 'paperless_billing',
 'payment_method']

In [33]:
df_full_train[categorical_features].nunique()

gender               2
senior_citizen       2
partner              2
dependents           2
phone_service        2
multiple_lines       3
internet_service     3
online_security      3
online_backup        3
device_protection    3
tech_support         3
streaming_tv         3
streaming_movies     3
contract             3
paperless_billing    2
payment_method       4
dtype: int64

## Feature importance

In [34]:
global_churn = df_full_train["churn"].mean()
global_churn

np.float64(0.26996805111821087)

In [35]:
churn_female = df_full_train[df_full_train["gender"] == "female"]["churn"].mean()
churn_male = df_full_train[df_full_train["gender"] == "male"]["churn"].mean()

churn_female, churn_male

(np.float64(0.27682403433476394), np.float64(0.2632135306553911))

In [36]:
global_churn - churn_female

np.float64(-0.006855983216553063)

In [37]:
global_churn - churn_male

np.float64(0.006754520462819769)

In [38]:
df_full_train["partner"].value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [39]:
churn_partner = df_full_train[df_full_train["partner"] == "yes"]["churn"].mean()
churn_no_partner = df_full_train[df_full_train["partner"] == "no"]["churn"].mean()

churn_partner, churn_no_partner

(np.float64(0.20503330866025166), np.float64(0.3298090040927694))

In [40]:
global_churn - churn_partner

np.float64(0.06493474245795922)

In [41]:
global_churn - churn_no_partner

np.float64(-0.05984095297455855)

$$\text{Risk Ratio} = \frac{\text{Group}}{\text{Global}}$$

- Risk = 1 -> group is as likely to churn as everyone else
- Risk > 1 -> group is more likely to churn
- Risk < 1 -> group is less likely to churn

In [42]:
churn_partner / global_churn

np.float64(0.7594724924338315)

In [43]:
churn_no_partner / global_churn

np.float64(1.2216593879412643)

In [44]:
for c in categorical_features:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(["mean", "count"])
    df_group["diff"] = df_group["mean"] - global_churn
    df_group["risk"] = df_group["mean"] / global_churn
    display(df_group)
    print("---\n")

gender

            mean  count      diff      risk
gender
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

---

senior_citizen

                    mean  count      diff      risk
senior_citizen
0               0.242270   4722 -0.027698  0.897403
1               0.413377    912  0.143409  1.531208

---

partner

             mean  count      diff      risk
partner
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

---

dependents

                mean  count      diff      risk
dependents
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

---

phone_service

                   mean  count      diff      risk
phone_service
no             0.241316    547 -0.028652  0.893870
yes            0.273049   5087  0.003081  1.011412

---

multiple_lines

                      mean  count      diff      risk
multiple_lines
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

---

internet_service

                      mean  count      diff      risk
internet_service
dsl               0.192347   1934 -0.077621  0.712482
fiber_optic       0.425171   2479  0.155203  1.574895
no                0.077805   1221 -0.192163  0.288201

---

online_security

                         mean  count      diff      risk
online_security
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

---

online_backup

                         mean  count      diff      risk
online_backup
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

---

device_protection

                         mean  count      diff      risk
device_protection
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

---

tech_support

                         mean  count      diff      risk
tech_support
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

---

streaming_tv

                         mean  count      diff      risk
streaming_tv
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

---

streaming_movies

                         mean  count      diff      risk
streaming_movies
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

---

contract

                    mean  count      diff      risk
contract
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

---

paperless_billing

                       mean  count      diff      risk
paperless_billing
no                 0.172071   2313 -0.097897  0.637375
yes                0.338151   3321  0.068183  1.252560

---

payment_method

                               mean  count      diff      risk
payment_method
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

---

The following features look important:
- `contract`
- `internet_service`
- `payment_method`

## Feature importance: Mutual information

In [45]:
from sklearn.metrics import mutual_info_score

In [46]:
mutual_info_score(
    df_full_train["churn"],
    df_full_train["contract"]
)

0.0983203874041556

In [47]:
mutual_info_score(
    df_full_train["churn"],
    df_full_train["gender"]
)

0.0001174846211139946

In [48]:
mutual_info_score(
    df_full_train["churn"],
    df_full_train["partner"]
)

0.009967689095399745

Note: Order of arguments doesn't matter because of symmetry

In [49]:
# Apply to every categorical column and sort the results from most to least importance

def mutual_info_churn_score(feature):
    return mutual_info_score(feature, df_full_train["churn"])

mis = df_full_train[categorical_features].apply(mutual_info_churn_score)
mis.sort_values(ascending=False)

contract             0.098320
online_security      0.063085
tech_support         0.061032
internet_service     0.055868
online_backup        0.046923
device_protection    0.043453
payment_method       0.043210
streaming_tv         0.031853
streaming_movies     0.031581
paperless_billing    0.017589
dependents           0.012346
partner              0.009968
senior_citizen       0.009410
multiple_lines       0.000857
phone_service        0.000229
gender               0.000117
dtype: float64

Essentially, mutual information is a measure of the importance of a categorical variable (how much we learn about the target if we have the information from a particular feature)

## Feature importance: Correlation

- LOW when the absolute value of r is between 0 and 0.2
- MEDIUM when it is between 0.2 and 0.5
- STRONG when it is between 0.5 and 1.0

In [50]:
df_full_train[numerical_features].corrwith(df_full_train["churn"])

tenure            -0.351885
monthly_charges    0.196805
total_charges     -0.196353
dtype: float64

In [51]:
df_full_train[numerical_features].corrwith(df_full_train["churn"]).abs()

tenure             0.351885
monthly_charges    0.196805
total_charges      0.196353
dtype: float64

In [52]:
# Max tenure in months
df_full_train["tenure"].max()

np.int64(72)

Double-check the correlation by splitting customers into groups and computing the churn rate in each

In [53]:
df_full_train[df_full_train["tenure"] <= 2]["churn"].mean()

np.float64(0.5953420669577875)

In [54]:
df_full_train[(df_full_train["tenure"] > 2) & (df_full_train["tenure"] <= 12)]["churn"].mean()

np.float64(0.3994413407821229)

In [55]:
df_full_train[df_full_train["tenure"] > 12]["churn"].mean()

np.float64(0.17634908339788277)

Negative correlation indeed shows that churn decreases as tenure increases

Same check for monthly charges

In [56]:
df_full_train[df_full_train["monthly_charges"] <= 20]["churn"].mean()

np.float64(0.08795411089866156)

In [57]:
df_full_train[(df_full_train["monthly_charges"] > 20) & (df_full_train["monthly_charges"] <= 50)]["churn"].mean()

np.float64(0.18340943683409436)

In [58]:
df_full_train[df_full_train["monthly_charges"] > 50]["churn"].mean()

np.float64(0.32499341585462205)

Positive correlation indeed shows that churn increases as monthly charge increases

## One-hot encoding

In [59]:
from sklearn.feature_extraction import DictVectorizer

In [60]:
df[categorical_features + numerical_features].to_dict(orient="records")[:5]

[{'gender': 'female',
  'senior_citizen': 0,
  'partner': 'yes',
  'dependents': 'no',
  'phone_service': 'no',
  'multiple_lines': 'no_phone_service',
  'internet_service': 'dsl',
  'online_security': 'no',
  'online_backup': 'yes',
  'device_protection': 'no',
  'tech_support': 'no',
  'streaming_tv': 'no',
  'streaming_movies': 'no',
  'contract': 'month-to-month',
  'paperless_billing': 'yes',
  'payment_method': 'electronic_check',
  'tenure': 1,
  'monthly_charges': 29.85,
  'total_charges': 29.85},
 {'gender': 'male',
  'senior_citizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phone_service': 'yes',
  'multiple_lines': 'no',
  'internet_service': 'dsl',
  'online_security': 'yes',
  'online_backup': 'no',
  'device_protection': 'yes',
  'tech_support': 'no',
  'streaming_tv': 'no',
  'streaming_movies': 'no',
  'contract': 'one_year',
  'paperless_billing': 'no',
  'payment_method': 'mailed_check',
  'tenure': 34,
  'monthly_charges': 56.95,
  'total_charges': 1889.5},
 {'gender': 'male',
  'senior_citizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phone_service': 'yes',
  'multiple_lines': 'no',
  'internet_service': 'dsl',
  'online_security': 'yes',
  'online_backup': 'yes',
  'device_protection': 'no',
  'tech_support': 'no',
  'streaming_tv': 'no',
  'streaming_movies': 'no',
  'contract': 'month-to-month',
  'paperless_billing': 'yes',
  'payment_method': 'mailed_check',
  'tenure': 2,
  'monthly_charges': 53.85,
  'total_charges': 108.15},
 {'gender': 'male',
  'senior_citizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phone_service': 'no',
  'multiple_lines': 'no_phone_service',
  'internet_service': 'dsl',
  'online_security': 'yes',
  'online_backup': 'no',
  'device_protection': 'yes',
  'tech_support': 'yes',
  'streaming_tv': 'no',
  'streaming_movies': 'no',
  'contract': 'one_year',
  'paperless_billing': 'no',
  'payment_method': 'bank_transfer_(automatic)',
  'tenure': 45,
  'monthly_charges': 42.3,
  'total_charges': 1840.75},
 {'gender': 'female',
  'senior_citizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phone_service': 'yes',
  'multiple_lines': 'no',
  'internet_service': 'fiber_optic',
  'online_security': 'no',
  'online_backup': 'no',
  'device_protection': 'no',
  'tech_support': 'no',
  'streaming_tv': 'no',
  'streaming_movies': 'no',
  'contract': 'month-to-month',
  'paperless_billing': 'yes',
  'payment_method': 'electronic_check',
  'tenure': 2,
  'monthly_charges': 70.7,
  'total_charges': 151.65}]

In [61]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_features + numerical_features].to_dict(orient="records")
X_train = dv.fit_transform(train_dict)
X_train.shape

(4225, 45)

In [62]:
val_dict = df_val[categorical_features + numerical_features].to_dict(orient="records")
X_val = dv.transform(val_dict)
X_val.shape

(1409, 45)

## Logistic regression: Binary classification

In [63]:
from sklearn.linear_model import LogisticRegression

In [64]:
model = LogisticRegression(solver="liblinear", random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1, solver='liblinear')

In [65]:
model.intercept_[0]

np.float64(-0.12193427062751563)

In [66]:
model.coef_[0].round(3)

array([ 0.607, -0.058, -0.671, -0.028, -0.094,  0.052, -0.103, -0.071,
       -0.042, -0.08 , -0.376,  0.357, -0.103,  0.002, -0.248,  0.133,
       -0.008,  0.057, -0.103, -0.076,  0.217, -0.103, -0.236, -0.249,
        0.127, -0.116, -0.006, -0.101, -0.049,  0.067, -0.04 ,  0.133,
       -0.255,  0.199, -0.101, -0.103,  0.082, -0.064, -0.103,  0.045,
        0.17 , -0.103, -0.189, -0.067,  0.   ])

## Predictions

In [67]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.00735886, 0.20972121, 0.22070809, ..., 0.14887941, 0.7848389 ,
       0.81058026], shape=(1409,))

In [68]:
churn_decision = (y_pred >= 0.5)
churn_decision

array([False, False, False, ..., False,  True,  True], shape=(1409,))

## Accuracy

In [69]:
(y_val == churn_decision).mean()

np.float64(0.8055358410220014)

About 80% of the cases the model predicted churn or no churn correctly

In [70]:
df_pred = pd.DataFrame()
df_pred["probability"] = y_pred
df_pred["prediction"] = churn_decision.astype(int)
df_pred["actual"] = y_val

df_pred["correct"] = (df_pred["prediction"] == df_pred["actual"])
df_pred["correct"].mean()

np.float64(0.8055358410220014)

## Model interpretation

In [71]:
dict(zip(dv.get_feature_names_out(), model.coef_[0].round(3)))

{'contract=month-to-month': np.float64(0.607),
 'contract=one_year': np.float64(-0.058),
 'contract=two_year': np.float64(-0.671),
 'dependents=no': np.float64(-0.028),
 'dependents=yes': np.float64(-0.094),
 'device_protection=no': np.float64(0.052),
 'device_protection=no_internet_service': np.float64(-0.103),
 'device_protection=yes': np.float64(-0.071),
 'gender=female': np.float64(-0.042),
 'gender=male': np.float64(-0.08),
 'internet_service=dsl': np.float64(-0.376),
 'internet_service=fiber_optic': np.float64(0.357),
 'internet_service=no': np.float64(-0.103),
 'monthly_charges': np.float64(0.002),
 'multiple_lines=no': np.float64(-0.248),
 'multiple_lines=no_phone_service': np.float64(0.133),
 'multiple_lines=yes': np.float64(-0.008),
 'online_backup=no': np.float64(0.057),
 'online_backup=no_internet_service': np.float64(-0.103),
 'online_backup=yes': np.float64(-0.076),
 'online_security=no': np.float64(0.217),
 'online_security=no_internet_service': np.float64(-0.103),
 'online_security=yes': np.float64(-0.236),
 'paperless_billing=no': np.float64(-0.249),
 'paperless_billing=yes': np.float64(0.127),
 'partner=no': np.float64(-0.116),
 'partner=yes': np.float64(-0.006),
 'payment_method=bank_transfer_(automatic)': np.float64(-0.101),
 'payment_method=credit_card_(automatic)': np.float64(-0.049),
 'payment_method=electronic_check': np.float64(0.067),
 'payment_method=mailed_check': np.float64(-0.04),
 'phone_service=no': np.float64(0.133),
 'phone_service=yes': np.float64(-0.255),
 'senior_citizen': np.float64(0.199),
 'streaming_movies=no': np.float64(-0.101),
 'streaming_movies=no_internet_service': np.float64(-0.103),
 'streaming_movies=yes': np.float64(0.082),
 'streaming_tv=no': np.float64(-0.064),
 'streaming_tv=no_internet_service': np.float64(-0.103),
 'streaming_tv=yes': np.float64(0.045),
 'tech_support=no': np.float64(0.17),
 'tech_support=no_internet_service': np.float64(-0.103),
 'tech_support=yes': np.float64(-0.189),
 'tenure': np.float64(-0.067),
 'total_charges': np.float64(0.0)}

For understanding, consider a smaller model

In [72]:
features_subset = ["contract", "tenure", "monthly_charges"]

dicts_train_small = df_train[features_subset].to_dict(orient="records")
dicts_val_small = df_val[features_subset].to_dict(orient="records")

dv_small = DictVectorizer(sparse=False)
dv_small.fit(dicts_train_small)

DictVectorizer(sparse=False)

In [73]:
dv_small.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'monthly_charges', 'tenure'], dtype=object)

In [74]:
X_train_small = dv_small.transform(dicts_train_small)

model_small = LogisticRegression()
model_small.fit(X_train_small, y_train)

LogisticRegression()

In [75]:
w0 = model_small.intercept_[0]
w0

np.float64(-2.477957596026966)

In [76]:
w = model_small.coef_[0]
dict(zip(dv_small.get_feature_names_out(), w.round(3)))

{'contract=month-to-month': np.float64(0.971),
 'contract=one_year': np.float64(-0.024),
 'contract=two_year': np.float64(-0.948),
 'monthly_charges': np.float64(0.027),
 'tenure': np.float64(-0.036)}

In [77]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [78]:
sample = -2.47 + (-0.948) + 0.027*30 + (-0.036)*24
print(sample)

sigmoid(sample).round(5) * 100

-3.472

np.float64(3.012)

One useful observation: the sigmoid of 0 is 0.5. So if the score is positive, the customer is more likely to churn than not; if it is negative, less likely.

## Final model

In [86]:
dicts_full_train = df_full_train[categorical_features + numerical_features].to_dict(orient="records")

dvf = DictVectorizer(sparse=False)
X_full_train = dvf.fit_transform(dicts_full_train)

y_full_train = df_full_train["churn"].values

In [87]:
model = LogisticRegression(solver="liblinear", random_state=1)
model.fit(X_full_train, y_full_train)

LogisticRegression(random_state=1, solver='liblinear')

In [88]:
# Check test set

dicts_test = df_test[categorical_features + numerical_features].to_dict(orient="records")
X_test = dvf.transform(dicts_test)

y_pred = model.predict_proba(X_test)[:,1]
churn_decision = (y_pred >= 0.5)
(churn_decision == y_test).mean()

np.float64(0.8126330731014905)

Accuracy on the test set is about 81.26%. On validation we had 80.3%. The two numbers are close, which is what we want to see: the model performs on unseen data about as well as on the data it was tuned with. A large gap between the two would be a sign of overfitting.

In [82]:
# Scoring one customer

customer = dicts_test[-1]
customer

{'gender': 'female',
 'senior_citizen': 0,
 'partner': 'yes',
 'dependents': 'yes',
 'phone_service': 'yes',
 'multiple_lines': 'yes',
 'internet_service': 'fiber_optic',
 'online_security': 'yes',
 'online_backup': 'no',
 'device_protection': 'yes',
 'tech_support': 'no',
 'streaming_tv': 'yes',
 'streaming_movies': 'yes',
 'contract': 'month-to-month',
 'paperless_billing': 'yes',
 'payment_method': 'electronic_check',
 'tenure': 17,
 'monthly_charges': 104.2,
 'total_charges': 1743.5}

In [83]:
X_small = dv.transform([customer])
model.predict_proba(X_small)[0,1]

np.float64(0.6434116288184129)

In [84]:
y_test[-1]

np.int64(1)

In [85]:
model.predict_proba(X_small)

array([[0.35658837, 0.64341163]])