# ML Zoomcamp 2026 – Homework 1

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# Q1
pd.__version__

'3.0.5'

In [3]:
data = Path("./data/car_fuel_efficiency_2026.csv").resolve()

df = pd.read_csv(data)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 1.1 MB

In [5]:
# Q2
df.shape

(10000, 11)

In [6]:
# Q3
df["fuel_type"].unique()

<ArrowStringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
# Q4
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
# Q5
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [9]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [10]:
median_prev = df["horsepower"].median()
median_prev

np.float64(254.0)

In [11]:
# Note that it's possible to have multiple modes in data
mode_hp = df["horsepower"].mode()[0]
print(mode_hp)

horsepowers = df["horsepower"].fillna(mode_hp)
print(horsepowers.isna().sum())

252.0
0

In [13]:
# Q6
median_new = horsepowers.median()
print(median_new)

median_new > median_prev

252.0

np.False_

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [14]:
asian_cars = df[df["origin"] == "Asia"]
asian_cars.info()

<class 'pandas.DataFrame'>
Index: 2994 entries, 2 to 9996
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           2994 non-null   int64
 1   origin               2994 non-null   str
 2   fuel_type            2994 non-null   str
 3   drivetrain           2994 non-null   str
 4   num_doors            2994 non-null   int64
 5   engine_displacement  2994 non-null   int64
 6   num_cylinders        2994 non-null   int64
 7   horsepower           2729 non-null   float64
 8   vehicle_weight       2994 non-null   int64
 9   acceleration         2994 non-null   float64
 10  fuel_efficiency_mpg  2994 non-null   float64
dtypes: float64(3), int64(5), str(3)
memory usage: 362.9 KB

In [15]:
asian_cars[["vehicle_weight", "model_year"]].iloc[:7]

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [19]:
X = asian_cars[["vehicle_weight", "model_year"]].iloc[:7].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [21]:
XTX = np.matmul(X.T, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [22]:
np.linalg.inv(XTX)

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [23]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [26]:
temp = np.matmul(np.linalg.inv(XTX), X.T)
w = np.matmul(temp, y)
w

array([0.13644777, 0.2327492 ])

In [28]:
# Q7
w.sum()

np.float64(0.36919696904925486)

Essentially, we calculate the vector of weights (coefficients) of the linear regression model using the normal equation.

$$
\mathbf{w} = (\mathbf{X}^\top \mathbf{X})^{-1} \mathbf{X}^\top \mathbf{y}
$$

Where:

- $\mathbf{X}$ is an $n \times (d+1)$ matrix of input features (including a column of 1s for the intercept).
- $\mathbf{w}$ is a $(d+1) \times 1$ vector of weights.
- $\mathbf{y}$ is an $n \times 1$ vector of target values.